name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: gm_common-Submodule
      run: git submodule update --init --recursive
      
     
    - name: Install Premake
      run: |
         curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-windows.zip -o premake.zip
         tar -xf premake.zip
          
    - name: Generate Project
      run: ./premake5.exe --gmcommon=garrysmod_common vs2019
      
    - name: Build 32
      run: |
        cd projects/windows/vs2019
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=ReleaseWithSymbols  /p:Platform=Win32 tickrate.sln
    
    - uses: actions/upload-artifact@v3
      with:
        name: gmsv_tickrate_win32.dll
        path: projects/windows/vs2019/x86/ReleaseWithSymbols /gmsv_tickrate_win32.dll
        
    - name: Build 64
      run: |
        cd projects/windows/vs2019
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=ReleaseWithSymbols  /p:Platform=x64 tickrate.sln
    
    - uses: actions/upload-artifact@v3
      with:
        name: gmsv_tickrate_win64.dll
        path: projects/windows/vs2019/x86_64/ReleaseWithSymbols /gmsv_tickrate_win64.dll
    
        
        
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: gm_common-Submodule
      run: git submodule update --init --recursive
      
    - name: Install Premake
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz -O premake.tar.gz
        sudo tar -xvf premake.tar.gz --directory=/usr/bin
        sudo apt-get update
        sudo apt-get install g++-multilib
        gcc --version
        
    - name: Generate Project
      run: |
        premake5 --gmcommon=garrysmod_common gmake
        
    - name: Make
      run: |
        cd projects/linux/gmake
        make
        make config=releasewithsymbols_x86_64
        
    - uses: actions/upload-artifact@v3
      with:
        name: gmsv_tickrate_linux.dll
        path: projects/linux/gmake/x86/ReleaseWithSymbols/gmsv_tickrate_linux.dll
        
    - uses: actions/upload-artifact@v3
      with:
        name: gmsv_tickrate_linux64.dll
        path: projects/linux/gmake/x86_64/ReleaseWithSymbols/gmsv_tickrate_linux64.dll
    
        
      
